server:
  port: 8085

spring:
  application:
    name: CangQiong

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_take_out?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 7758521
  data:
       redis:
         port: 19383
         host: localhost


sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

static:
  path: /Users/ayong/ayong-code/java/static/
